name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  dio: ^5.3.0
  logger: any
  flutter_dotenv: ^5.1.0
  hive: ^2.2.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
