name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  dio: ^5.5.0
  firebase_analytics: ^11.1.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  
  hive: ^2.2.3
  intl: ^0.19.0
  logger: ^2.3.0
  stacked: ^3.4.3
  stacked_services: ^1.5.0  

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  stacked_generator: ^1.6.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
